### ISSUE TITLE
Method getConfigValue published?

### ISSUE THREAD

**Issue by Nic2012** [lwille/node-gphoto2#104]
I am trying to get the value from one prop only e.g.:
```
 camera.getConfigValue('shutterspeed2', function (err, settings) {
    if (err) {
      console.error('getConfigValue', err);
    }
    console.log('getConfigValue', JSON.stringify(settings,null,2));
  });
```
But it returns
```
  camera.getConfigValue('shutterspeed2', function (err, settings) {
         ^

TypeError: camera.getConfigValue is not a function
```
I dont want to call always getConfig, it cost too much time and produces a lot of data. gphoto2 cli delivers as a standard "--get-config=STRING] [--set-config=STRING" getter and setter on each prop.

BTW could y extend the doc by declaring the public methods what can we use in node.

Thanks for providing us this binding, it helps a lot.
Best regards,
Nic

**Comment by Sija** [comment]
This particular method indeed is not implemented, PRs are welcome!

**Comment by Nic2012** [comment]
BTW there is another basic method missing, too:
e.g:
```
gphoto2 --storage-info
[Storage 0]
label=NIKON D700
basedir=/store_00010001
access=2 Read-only with delete
type=4 Removable RAM
fstype=4 Camera layout (DCIM)
totalcapacity=7822432 KB
free=7473024 KB
freeimages=699
```

**Comment by apsylone** [comment]
That's a bit strange because the method is declared in the header files but not implemented.
I would love to implement it by my side, but I don't have the skills too.

Hope it'll be implemented in a next release :-)

**Comment by lwille** [comment]
Closing this very old feature request; feel free to reopen if somebody finds the time to suggest an implementation.
