### ISSUE TITLE
Capture movie with lib ?

### ISSUE THREAD

**Issue by apsylone** [lwille/node-gphoto2#126]
Hi,

I Would like to know if it is possible to capture a movie with this library ?
The capture works with the binary when executing this command : 
"gphoto2 --set-config movie=1 --wait-event=10s --set-config movie=0 --wait-event-and-download=2s"

But it doesn't download it... But it is saved on the camera. That's a great beginning :-) 

But know, I would like to know "how to" with this library ? But I see a takePicture function, but no more...

Thanks for the help :-)

**Comment by lwille** [comment]
Hi! I know it's been a while since this was asked, but still:

This library is just a wrapper around `libgphoto2`. To give you a pointer, here's what you could do:
- use `takePicture` and `writeFile` to write a bunch of jpeg frames to disk
- use `ffmpeg` to combine these frames into a movie.
