### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by maaqoul** [lwille/node-gphoto2#127]
is there a way i can make my app work on a windows os, how should i go about it ? what should i learn ?

**Comment by positlabs** [comment]
Have you tried Docker? That would let you run linux on windows

**Comment by maaqoul** [comment]
is there a resource i can use to learn this ? thank you for your answer !

**Comment by positlabs** [comment]
https://docs.docker.com/get-started/

**Comment by maaqoul** [comment]
thank you
