### ISSUE TITLE
error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’

### ISSUE THREAD

**Issue by jtleniger** [lwille/node-gphoto2#129]
Can't build due to this error.

Seems to be coming from constructor.Reset(tpl->GetFunction()); in gphoto.cc and camera.cc.

Any ideas?

**Comment by jtleniger** [comment]
`../src/gphoto.cc:55:38: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   constructor.Reset(tpl->GetFunction());`

**Comment by lwille** [comment]
Hey! Can you please describe your environment, most importantly node version and OS type (Linux/Darwin)?

**Comment by jtleniger** [comment]
Hello! I think it may be related to the Lubuntu distro I was using, perhaps. I tried it again on a fresh Ubuntu box with no issues.

**Comment by lwille** [comment]
I'm assuming that this can be closed.
