### ISSUE TITLE
After using "takePicture" the camera is stuck. 

### ISSUE THREAD

**Issue by Antoni-Petrenko** [lwille/node-gphoto2#136]
After using "takePicture" the camera is stuck. Then when I need to make the next photo I get the message that the PTP Device Busy

But when I use CLI gphoto2 --capture-image
everything works fine.

I use NodeJS 12.13.0
Camera summary:
Manuf: Nikon Corp
Model: D5100

**Comment by lwille** [comment]
Hi @Antoni-Petrenko, would you mind sharing a code snippet that indicates how you're using `takePicture`?

**Comment by lwille** [comment]
Closing issue for a lack of feedback.
