### ISSUE TITLE
please make a release

### ISSUE THREAD

**Issue by phatpaul** [lwille/node-gphoto2#150]
Thanks for this handy library.

Took me a little while just to find out I needed the functionality added here:
https://github.com/lwille/node-gphoto2/commit/7e43c75496204ea76d9262cf567949cda50a8baf
https://github.com/lwille/node-gphoto2/pull/132
Which is not included in the latest release 0.3.2 (4 years ago).

For now, I got the latest code like this:
`npm install --save lwille/node-gphoto2`

**Comment by Sija** [comment]
This library is not maintained anymore, there's no point in doing a new release.

**Comment by phatpaul** [comment]
That's annoying.  How was I supposed to know that it isn't maintained?

**Comment by Sija** [comment]
Looking at the commit list should be enough. In any case you know now.
