### ISSUE TITLE
npm install fails on MAC 10.9.3

### ISSUE THREAD

**Issue by plkumar** [lwille/node-gphoto2#57]
npm install fails on MAC 10.9.3 see the log below, it says 'gphoto2/gphoto2-camera.h' not found while it is there in the right path.

Appreciate some help here.

> gphoto2@0.1.7-pre preinstall /Users/lakshman/node-gphoto2
> ((which pkg-config && pkg-config libgphoto2) || (which dpkg && dpkg -s libgphoto2-2-dev) || (which brew && brew list libgphoto2) || (echo 'ERROR: libgphoto2 seems not to be installed.' 1>&2; exit 1)) && node-gyp rebuild

/opt/local/bin/pkg-config
/usr/local/bin/brew
/usr/local/Cellar/libgphoto2/2.5.1/bin/gphoto2-port-config
/usr/local/Cellar/libgphoto2/2.5.1/bin/gphoto2-config
/usr/local/Cellar/libgphoto2/2.5.1/include/gphoto2/ (18 files)
/usr/local/Cellar/libgphoto2/2.5.1/lib/libgphoto2.6.dylib
/usr/local/Cellar/libgphoto2/2.5.1/lib/libgphoto2_port.10.dylib
/usr/local/Cellar/libgphoto2/2.5.1/lib/libgphoto2/ (65 files)
/usr/local/Cellar/libgphoto2/2.5.1/lib/libgphoto2_port/ (7 files)
/usr/local/Cellar/libgphoto2/2.5.1/lib/pkgconfig/ (2 files)
/usr/local/Cellar/libgphoto2/2.5.1/lib/udev/check-ptp-camera
/usr/local/Cellar/libgphoto2/2.5.1/lib/ (2 other files)
/usr/local/Cellar/libgphoto2/2.5.1/share/doc/ (54 files)
/usr/local/Cellar/libgphoto2/2.5.1/share/libgphoto2/ (6 files)
/usr/local/Cellar/libgphoto2/2.5.1/share/man/ (2 files)
  CXX(target) Release/obj.target/gphoto2/src/autodetect.o
../src/autodetect.cc:3:10: fatal error: 'gphoto2/gphoto2-camera.h' file not
      found
# include <gphoto2/gphoto2-camera.h>

```
     ^
```

1 error generated.
make: **\* [Release/obj.target/gphoto2/src/autodetect.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:215:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! System Darwin 13.2.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/lakshman/node-gphoto2
gyp ERR! node -v v0.8.5
gyp ERR! node-gyp -v v0.6.3
gyp ERR! not ok 
npm ERR! gphoto2@0.1.7-pre preinstall: `((which pkg-config && pkg-config libgphoto2) || (which dpkg && dpkg -s libgphoto2-2-dev) || (which brew && brew list libgphoto2) || (echo 'ERROR: libgphoto2 seems not to be installed.' 1>&2; exit 1)) && node-gyp rebuild`
npm ERR! `sh "-c" "((which pkg-config && pkg-config libgphoto2) || (which dpkg && dpkg -s libgphoto2-2-dev) || (which brew && brew list libgphoto2) || (echo 'ERROR: libgphoto2 seems not to be installed.' 1>&2; exit 1)) && node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the gphoto2@0.1.7-pre preinstall script.
npm ERR! This is most likely a problem with the gphoto2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ((which pkg-config && pkg-config libgphoto2) || (which dpkg && dpkg -s libgphoto2-2-dev) || (which brew && brew list libgphoto2) || (echo 'ERROR: libgphoto2 seems not to be installed.' 1>&2; exit 1)) && node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls gphoto2
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/lakshman/node-gphoto2
npm ERR! node -v v0.8.5
npm ERR! npm -v 1.1.46
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/lakshman/node-gphoto2/npm-debug.log
npm ERR! not ok code 0

**Comment by roowilliams** [comment]
Just tried to clone my app on a 10.10 Mac with freshly installed node and have the same problem.

**Comment by roowilliams** [comment]
I used [nvm](https://github.com/creationix/nvm)  to install and use node 0.10.0 and installed properly.

**Comment by chameleooo** [comment]
I had the same problem and the symlink seems to fix it.
Thank you !

You can also install node 0.10 via brew if you don't want to install nvm:
http://www.wiredatom.com/blog/2015/03/30/downgrade-node-js-to-a-specific-version-using-homebrew/

**Comment by jmsaavedra** [comment]
+1 also had this issue when using Node installed via nvm.

Symlink hack fixed it (although is very hacky and not ideal...):

```
sudo ln -s /usr/local /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/local
```
thank you @ncrohn !

**Comment by gabrielstuff** [comment]
Thanks ! Indeed, with El capitan, you might want to run : 

`sudo ln -s /usr/local /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/local`

**Comment by truefalse10** [comment]
For MacOSX10.12 you might run:
`sudo ln -s /usr/local /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/local`
