### ISSUE TITLE
takePicture a file descriptor opened causing "too many files opened" error

### ISSUE THREAD

**Issue by rformato** [lwille/node-gphoto2#61]
It seems like each time takePicture is called, a new file descriptor is created and never closed, bringing to an error in the long run when no more file descriptor can be created.

You can just loop a takePicture call and launch this shell command
`lsof | grep node`

to see how many opened files you have

Can you confirm it's a file descriptor leak?

**Comment by lwille** [comment]
Should be fixed in 0.1.7 (ba9a9b9)
