### ISSUE TITLE
Compilation fails on node.js v0.12

### ISSUE THREAD

**Issue by Sija** [lwille/node-gphoto2#65]
There's hefty stack of compilation errors on `v0.12`.
Do you plan to support this version?
In terms of maintaining cross-version compatibility [rvagg/nan](https://github.com/rvagg/nan) might be worth looking at.

**Comment by lwille** [comment]
Thanks for testing!I think that's a call for a complete rewrite. Is anyone up to help with that?

**Comment by kjantzer** [comment]
Errors too. 
```
/usr/local/Cellar/libgphoto2/2.5.7/share/man/ (2 files)
  CXX(target) Release/obj.target/gphoto2/src/autodetect.o
../src/autodetect.cc:3:10: fatal error: 'gphoto2/gphoto2-camera.h' file not found
#include <gphoto2/gphoto2-camera.h>
         ^
1 error generated.
make: *** [Release/obj.target/gphoto2/src/autodetect.o] Error 1
```

You can see that the file it could not find appears to be there:
![screen shot 2015-02-16 at 8 46 06 pm](https://cloud.githubusercontent.com/assets/467487/6223395/e4676c16-b61c-11e4-85f8-4a0fb7332812.png)

**Comment by lwille** [comment]
@kjantzer this is rather a library path issue with homebrewed libraries.

**Comment by kjantzer** [comment]
Hmmm. Ok, I'll have to see what I can figure out. Thanks

**Comment by lwille** [comment]
Started porting it to [rvagg/nan](https://github.com/rvagg/nan); I'll publish a branch once the wheather in Berlin gets bad again :sun_with_face:
