### ISSUE TITLE
Preview stream

### ISSUE THREAD

**Issue by lwille** [lwille/node-gphoto2#69]
Streaming of preview pictures, possibly in MJPEG format
related: #64 
- [ ] Find out how to properly stream data from C++ to Node
- [ ] Run a timed loop in the C++ part to fetch preview pictures
- [ ] Provide single JPEGs as well as continuous MJPEG stream

**Comment by LoganArnett** [comment]
Im assuming that this is just a dead feature? This would be very useful if implemented

**Comment by lwille** [comment]
@LoganArnett totally. I was researching into MJPEG streaming back then, but never got it to work in a performant way.
