### ISSUE TITLE
"Could not claim the USB device"

### ISSUE THREAD

**Issue by Nic2012** [lwille/node-gphoto2#78]
Hi,
at first many thanks for y great work and offering this bindings to the community.

I would like to implement the node bindings inside a node (http-) server app that is permanently running, but it seems that the gphoto objects locks exclusively the usb port as long my app is running. If I want access gphoto2 cli from command line simultanously i get the above message.
Sometimes y want to disconnect camera from node bindings to access from other sides.

Think about the case if battery is empty and the camera isnt accessible anymore. Is there any chance to disconnect the camera by a command and reconnect it again after a while.

I am not a pro in C++ but it seems in y code internally y are using closeCamera and openCamera, would it be possible to provide this methods as public ?

It seems that the stdout messages in general are not fully routed through the bindings. If i set my capture settings burstnumber=2 for example, the camera will shot 2 pictures immediatly in a row, but the result the stdout returns always the last file path instead of all lines.

It would a great help if y explain node bindings with more examples as mentioned. I wasnt lucky in 1st mom in setting capturetarget on my Nikon D700 by y example
camera.setConfigValue('capturetarget', 1, function (er) {//...});

But what works for me is
camera.setConfigValue('capturetarget', 'Memory card', function (er) {//...});

So could it be that overgiven value in correct type is dependent from camera manufacturer ?

Best regards,
Nic

**Comment by lwille** [comment]
Please reopen if the problem persists.
