### ISSUE TITLE
Cannot install on rpm based system

### ISSUE THREAD

**Issue by moimael** [lwille/node-gphoto2#80]
Hi,

I tried to install gphoto2 using npm under fedora 23 but failed. It seems that this line is faulty : 

```
"preinstall": "((which pkg-config && pkg-config libgphoto2) || (which dpkg && dpkg -s libgphoto2-2-dev) || (which brew && brew list libgphoto2) || (echo 'ERROR: libgphoto2 seems not to be installed.' 1>&2; exit 1)) && node-gyp rebuild"
```

for me pkg-config libgphoto2 doest not return anything, despite being installed (in normal and devel version). Maybe you should add some rpm command in this ?

Thanks !

**Comment by Sija** [comment]
Closing due to the age of the issue, reopen if needed.
