### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by auterium** [lwille/node-gphoto2#81]
First of all, thanks for this awesome library, it's been very helpful to me.

I need to be able to listen for disconnection/reconnection of the camera. To do so, I execute multiple times the list() method. After many tests, I found out that calling this method ads ~5MB of ram usage that never gets cleaned up. Here's some code to test the leakage:

``` javascript
var GPhoto2 = require("gphoto2").GPhoto2;
var os = require("os");
var gp = new GPhoto2();

setIntervar(function() {
  gp.list(function(list) {
    console.log(os.freemem());
  });
}, 1000);
```

Thanks

**Comment by Sija** [comment]
@lwille Issue is still there, isn't it?

**Comment by Sija** [comment]
@lwille nope, this fix was too naïve so I removed it after all.
