### ISSUE TITLE
gphoto2.node invalid ELF header

### ISSUE THREAD

**Issue by aceol** [lwille/node-gphoto2#82]
Hello, 
 I had troubles installing gphoto2 module on my raspberry/rasbian distrib. I had to install it via sudo or it was failing with no explicit message.
Now it is installed via 
`sudo npm install --save gphoto2`

`"gphoto2": "^0.1.7"`

```
gphoto2 -v
gphoto2 2.5.4
```

when I run my app with gphoto2 loaded
`var gphoto2 = require("gphoto2");`

```
module.js:440
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/pi/projet/maton/node_modules/gphoto2/build/Release/gphoto2.node: invalid ELF header
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/projet/maton/web.js:11:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

Is there anything wrong with my installation?
Thanks a lot for any help,

**Comment by Sija** [comment]
Maybe `[sudo] npm rebuild gphoto2` will do (see [documentation](https://docs.npmjs.com/cli/rebuild))...?

**Comment by aceol** [comment]
Thanks Sija, unfortunately, it does'nt fix the issue.

**Comment by lwille** [comment]
This module is very outdated and doesn't compile against recent node
versions.
If you want to use it, you're bound to node ~0.10.0

-- 
Leonhardt Wille

**Comment by aceol** [comment]
I was afraid so Leonhardt. 
Do you know of any related node projects?
Anyway, thanks for your anwser and for the great work so far.

**Comment by lwille** [comment]
There might be wrappers around the gphoto2 CLI that could fulfill what
you're trying to achieve.
You could as well look into libs for other languages like python.

Good luck with your project!

-- 
Leonhardt Wille

**Comment by Sija** [comment]
See #67, closing.
