### ISSUE TITLE
Problem with "npm install gphoto2" - Mac OS X 10.12

### ISSUE THREAD

**Issue by apsylone** [lwille/node-gphoto2#84]
Hi, 

I met a problem when trying to install via NPM on Mac OS X 10.12 beta 2 (Sierra).

~ node --version
v6.2.1

~ npm --version
3.9.3

~ brew info libgphoto2
libgphoto2: stable 2.5.10, HEAD

~  npm install gphoto2
Results : https://gist.github.com/apsylone/9ef4aebd9f173b515749150c4473225b

~ cat npm-debug.log
Results : https://gist.github.com/apsylone/739a3f26293b8ec13fa60744239b6f99

**Comment by Sija** [comment]
See #83

**Comment by apsylone** [comment]
You're right. It solves part of my issue. Haven't seen it because it was closed.
Sorry and thanks for your message. 👍
