### ISSUE TITLE
Continuous lock-up issue

### ISSUE THREAD

**Issue by goudarziha** [lwille/node-gphoto2#85]
I can only change the config settings for a Cannon T5i only a few number of times before I get the -110 ( camera lockup code) Where it would require me to start the camera in order to change any other settings. I am currently changing one setting at a time, but is there any other more efficient way to escape this error from having to restart the camera over and over again?

Thanks.

**Comment by Sija** [comment]
Does it work with command line `gphoto2`?

**Comment by lwille** [comment]
After countless hours I didn't find a way out of the `-110` state.

Back in the days, my solution was to use USB-controllable power switch to power cycle the camera's AC adaptor.
Today I'd use a Raspberry Pi's GPIO pin to interrupt the 5V DC power of the camera, as I'd use a Pi Zero to control the camera.

Alternatively try to dump and load the settings with `gphoto2`. 
If it doesn't expose this behavior, it might be worth to debug it to see what they're doing differently.

**Comment by lwille** [comment]
I'm closing this due to lack of feedback and age of the issue.
