### ISSUE TITLE
Working on a node-ffi API for gphoto2

### ISSUE THREAD

**Issue by PoignardAzur** [lwille/node-gphoto2#89]
Hello.

I wanted to pop by and say that I'm currently working on a Node.js port of the gphoto2 library for my company, using the node-ffi module. Node-ffi is an automated API for porting C libraries into Node project; it only needs .so/.dll files and a list of prototypes and it's good to go!

My work so far (I've mostly been studying node-ffi): https://github.com/PoignardAzur/tests_gphoto2

Is this project still going? It hasn't been updated in a while.

**Comment by smuser90** [comment]
Considering this module is recommended with Node v0.10 I'd say it's a little outdated ;) 
I've been using it to prototype some work though and as long as you have a compatible version of V8 it works well. 

How have you found using node-ffi with libgphoto so far? I hadn't heard of node-ffi before and I'm really intrigued by that approach!

**Comment by PoignardAzur** [comment]
Well it has its qualities and its drawbacks.

Main quality is that you need very little code to port a large number of functions; main drawback is that it's C only, and it's based on C logic in general (so no objects, no RAII, no exceptions, etc, you have to add them yourself). Overall I'd say it's pretty good.

**Comment by Sija** [comment]
Closing since it's not really an issue.
Updates coming in #94.
